---
title: Me
timezone: Asia/Bangkok
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/me"
url: https://minibugdev.github.io/
theme_settings:
  title: Minibug's Journey
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: bf76b929fe4181c32c4f239dfe754955
  description: Welcome to my life's journey.
  header_text: |
    <h3>Life is about courage and going into the unknown.</h3>
    <p class="meta">― The Secret Life of Walter Mitty</p>
  header_text_feature_image: assets/img/home_feature.webp
  footer_text: 'Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type
    Theme</a>

'
  rss: false
  email_address: minibugdev@gmail.com
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  gitlab: 
  github: minibugdev
  gitter: 
  google_plus: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  tumblr: 
  twitter: 
  wordpress: 
  youtube: 
  google_analytics: 
  disqus_shortname: 
  katex: false
  search: false
  str_follow_on: Follow on
  str_rss_follow: Follow RSS feed
  str_email: Email
  str_next_post: Next post
  str_previous_post: Previous post
  str_next_page: Next
  str_previous_page: Prev
  str_continue_reading: Continue reading
  str_javascript_required_disqus: Please enable JavaScript to view comments.
  str_search_no_results: No results found.
  google_fonts: Raleway|Roboto:300,600,600italic,300italic
  post_navigation: false
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: highlight
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
